M48
; DRILL file {KiCad (6.0.0)} date Sun Feb 13 20:02:53 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-13T20:02:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X28.956Y-18.61
X28.956Y-62.992
X87.982Y-18.61
X87.982Y-63.06
T0
M30
